// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsa4zYWyoDxZnR1kVbaDrh3WExKptACuI',
    appId: '1:972027550217:web:e16fa3a9240f35b23db6d8',
    messagingSenderId: '972027550217',
    projectId: 'animetv-1ae1e',
    authDomain: 'animetv-1ae1e.firebaseapp.com',
    storageBucket: 'animetv-1ae1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpW79ftDTlAplGjeWorZkSKbXfvkVa6cY',
    appId: '1:972027550217:android:d92abed5ce0ae3e23db6d8',
    messagingSenderId: '972027550217',
    projectId: 'animetv-1ae1e',
    storageBucket: 'animetv-1ae1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUfsG1tNkLL2ikjgbcozsOpCfSU8k2Z-U',
    appId: '1:972027550217:ios:feca0d789d9716673db6d8',
    messagingSenderId: '972027550217',
    projectId: 'animetv-1ae1e',
    storageBucket: 'animetv-1ae1e.appspot.com',
    iosClientId: '972027550217-gsdc4vqrn8funbrrdunqevfot5sgjsg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.animetv',
  );
}
